FROM python:3.10-slim

WORKDIR /app


# Install system dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy application files
COPY worker_pubsub.py .
COPY worker.py .
COPY config.py .

# Run worker pub/sub
CMD ["python", "worker_pubsub.py"]
